name: Compatibility

on:
  workflow_dispatch:

jobs:
  compatibility:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jmeter: ["5.6.3"]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
      - run: cd packages/java-bridge && gradle test
